<a href="https://colab.research.google.com/github/Rishabh6066/numpy_initial/blob/main/Numpy_Codenera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ADVANCED PYTHON STARTED**

In [ ]:
'''
What is NumPy?

NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
NumPy stands for Numerical Python.

Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make
working with ndarray very easy.
Arrays are very frequently used in data science, where speed and resources are very important.
Data Science: is a branch of computer science where we study how to store, use and analyze
 data for deriving information from it.

Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access
and manipulate them very efficiently.
This behavior is called locality of reference in computer science.
This is the main reason why NumPy is faster than lists. Also it is optimized to work with
latest CPU architectures.


Which Language is NumPy written in?

NumPy is a Python library and is written partially in Python,
 but most of the parts that require fast computation are written in C or C++.
'''

'\nWhat is NumPy?\n\nNumPy is a Python library used for working with arrays.\nIt also has functions for working in domain of linear algebra, fourier transform, and matrices.\nNumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.\nNumPy stands for Numerical Python.\n\nWhy Use NumPy?\n\nIn Python we have lists that serve the purpose of arrays, but they are slow to process.\nNumPy aims to provide an array object that is up to 50x faster than traditional Python lists.\nThe array object in NumPy is called ndarray, it provides a lot of supporting functions that make\nworking with ndarray very easy.\nArrays are very frequently used in data science, where speed and resources are very important.\nData Science: is a branch of computer science where we study how to store, use and analyze\n data for deriving information from it.\n\nWhy is NumPy Faster Than Lists?\n\nNumPy arrays are stored at one continuous place in memory unlike lists, so processes 

In [ ]:
'''
Array-
    Collection of Homogeneous data,
    indexed and ordered, allows duplicated values, mutable(can do changes.)
'''

Creating an array


In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


O-D Array

In [ ]:
arr= np.array('a')
print(arr)

print(arr)
print(type(arr))
print('Dimension of array arr:',arr.ndim,'dimension') # ndim means as n-no. dim-dimensions

a
a
<class 'numpy.ndarray'>
Dimension of array arr: 0 dimension


1-D array

In [ ]:
arr= np.array([1,2,3,4,5,6,7,8])
print(arr)

print(arr)
print(type(arr))
print('Dimension of array arr:',arr.ndim,'dimension')

[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
Dimension of array arr: 1 dimension


2-D array

In [ ]:
arr= np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]
             ])
print(arr)
print(type(arr))
print('Dimension of array arr:',arr.ndim,'dimension')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>
Dimension of array arr: 2 dimension


3-D arrray

In [ ]:
arr= np.array([
            [
                [1,2,3],
                [4,5,6]
            ],
            [
                [11,12,13],
                [14,15,16]
            ],
            [
                [21,22,23],
                [24,25,26]
            ]
             ])
print(arr)
print(type(arr))
print('Dimension of array arr:',arr.ndim,'dimension')

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]
<class 'numpy.ndarray'>
Dimension of array arr: 3 dimension


n-D Array / (Multiple Dimensional array)

In [ ]:
arr= np.array([1,2,3],ndmin=5)
print(arr)

print(arr)
print(type(arr))
print('Dimension of array arr:',arr.ndim,'dimension')

[[[[[1 2 3]]]]]
[[[[[1 2 3]]]]]
<class 'numpy.ndarray'>
Dimension of array arr: 5 dimension


In [ ]:
arr= np.araay([1,2,3.,'5'])
print(arr)
'''
If we create an array(hetrogeneous)
'''

AttributeError: module 'numpy' has no attribute 'araay'

Indexing

In [ ]:
arr= np.array([1,2,3,4,5,6,7,8])

for 2D


In [ ]:
arr= np.array([
                [1,2,3],
                [4,5,6],
             ])
print(arr[0])
print(arr[1])

print(arr[0][0])
print(arr[0][1])
print(arr[0][2])

print(arr[1][0])
print(arr[1][1])
print(arr[1][2])


[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [ ]:
arr= np.array([
                [1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15]

             ])

print(arr[0])
print(arr[1])
print(arr[2])

print(arr[0][0])
print(arr[0][1])
print(arr[0][2])
print(arr[0][3])
print(arr[0][4])

print(arr[1][0])
print(arr[1][1])
print(arr[1][2])
print(arr[1][3])
print(arr[1][4])


[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
1
2
3
4
5
6
7
8
9
10


Range()

In [ ]:
# 8 extract
print(arr)
print(arr[1][-3])



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
8


In [ ]:
arr= np.array([
                [66,32,22],
                [89,79,32],
                [100,22,379]
             ])

# -ve range: list 2 last 2 element

print(arr[2][-2:])



[ 22 379]


In [ ]:
arr= np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
             ])


#[[1 3]
# [7 9]]
print(arr[::2,::2])

[[1 3]
 [7 9]]


Extra

In [ ]:
arr= np.array([
                [1,2,3],
                [4,5,6],
                [11,20,23],
                [14,56,68]
])

print(arr[2:,::2])

print(arr[1::2,::2])

print(arr[::3,::-2])

print(arr[::,::-1])

print(arr[::-1,::-1])

[[11 23]
 [14 68]]
[[ 4  6]
 [14 68]]
[[ 3  1]
 [68 14]]
[[ 3  2  1]
 [ 6  5  4]
 [23 20 11]
 [68 56 14]]
[[68 56 14]
 [23 20 11]
 [ 6  5  4]
 [ 3  2  1]]


In [ ]:
arr= np.array([
            [
                [1,2,3],
                [4,5,6]
            ]
            [
               [11,20,23],
               [14,15,16]
            ]
            [
                [21,22,23],
                [24,25,26]
            ]

])

print(arr[::-1,::-1,::-1])

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-2-931f888e7551>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [


TypeError: list indices must be integers or slices, not tuple

In [ ]:
# create a 3*3 2d array and
# find the elements that are on the edges of array,
# each first and last element of all the rows,
# middle element of the array
# using slicing



import numpy as np

In [ ]:
import numpy as np


arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]  ])
print("elements that are on the edges of array")
print(arr[::2,::2])
print("each first and last element of all the rows")
print(arr[:,::2])
print("middle element of the array")
print(arr[1, 1])
print("middle column element of array")
print(arr[:,1])


elements that are on the edges of array
[[1 3]
 [7 9]]
each first and last element of all the rows
[[1 3]
 [4 6]
 [7 9]]
middle element of the array
5
middle column element of array
[2 5 8]


In [ ]:
# create 4*5 array find the elements
# Eg:
# * * * * *
# * 1 2 3 *
# * 4 5 6 *
# * * * * *
# slice 1,3,4,6

In [ ]:

arr = np.array([
    [0, 0, 0, 0, 0],
    [0, 1, 2, 3, 0],
    [0, 4, 5, 6, 0],
    [0, 0, 0, 0, 0]
])
print(arr)

sliced_elements = [arr[1, 1], arr[1, 3], arr[2, 1], arr[2, 3]]

print(sliced_elements)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 0 0 0 0]]
[1, 3, 4, 6]


3D array slicing

In [ ]:

arr = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[11, 12, 13],
     [14, 15, 16],
     [17, 18, 19]],

    [[21, 22, 23],
     [24, 25, 26],
     [27, 28, 29]]
])

print(arr)
print("Number of dimensions:", arr.ndim)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
Number of dimensions: 3


In [ ]:
print("a 2d array on 2-0 in 3d array")
print(arr[0])

print("a 2d array on 2-1 in 3d array")
print(arr[1])

print("a 2d array on 2-2 in 3d array")
print(arr[2])

a 2d array on 2-0 in 3d array
[0 0 0 0 0]
a 2d array on 2-1 in 3d array
[0 1 2 3 0]
a 2d array on 2-2 in 3d array
[0 4 5 6 0]


In [ ]:
print(arr[0][0])
print(arr[0][1])
print(arr[0][2])

print(arr[1][0])
print(arr[1][1])
print(arr[1][2])

print(arr[2][0])
print(arr[2][1])
print(arr[2][2])

#first and last row from 2-0
print("first and last row from 2-0")
print(arr[0,::2])

#first and last row from first and last 2d arrays
print("first and last row from first and last 2d arrays")
print(arr[::2,::2])

0
0
0
0
1
2
0
4
5
first and last row from 2-0
[0 0 0]
first and last row from first and last 2d arrays
[[0 0 0]
 [0 5 0]]


In [ ]:
# z-0 y-0
print('(0,0,0)',arr[0][0][0])
print('(0,0,1)',arr[0][0][1])
print('(0,0,2)',arr[0][0][2])

#z-0 y-1
print('(0,1,0)',arr[0][1][0])
print('(0,1,1)',arr[0][1][1])
print('(0,1,2)',arr[0][1][2])

#z-0 y-2
print('(0,2,0)',arr[0][2][0])
print('(0,2,1)',arr[0][2][1])
print('(0,2,2)',arr[0][2][2])

#z-1 y-0
print('(1,0,0)',arr[1][0][0])
print('(1,0,1)',arr[1][0][1])
print('(1,0,2)',arr[1][0][2])

#z-1 y-1
print('(1,1,0)',arr[1][1][0])
print('(1,1,1)',arr[1][1][1])
print('(1,1,2)',arr[1][1][2])

#z-1 y-2
print('(0,2,0)',arr[1][2][0])
print('(1,2,1)',arr[1][2][1])
print('(1,2,2)',arr[1][2][2])

#z-2 y-0
print('(2,0,0)',arr[2][0][0])
print('(2,0,1)',arr[2][0][1])
print('(2,0,2)',arr[2][0][2])

# z-2 y-1
print('(2,1,0)',arr[2][1][0])
print('(2,1,2)',arr[2][1][1])
print('(2,1,2)',arr[2][1][2])

#z-2 y-2
print('(2,2,0)',arr[2][2][0])
print('(2,2,1)',arr[2][2][1])
print('(2,2,2)',arr[2][2][2])

IndexError: invalid index to scalar variable.

In [ ]:
print("first and last row from 2-0")
print(arr[0,::2])

print(arr[::2])

print(arr[::2,1,::2])

first and last row from 2-0
[0 0 0]
[[0 0 0 0 0]
 [0 4 5 6 0]]


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [ ]:
'''
[[13,11],
[19,17]]
'''
print(arr[1, ::2, ::-2] )

arr = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[11, 12, 13],
     [14, 15, 16],
     [17, 18, 19]],

    [[21, 22, 23],
     [24, 25, 26],
     [27, 28, 29]]
])

print(arr)

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [ ]:
'''
[[3,1]
[9,7]]
[[23 21]
[29 27]]
'''
print(arr[::2,::2,::-2])



In [ ]:
'''
[[23 21]
[29 27]]
[[3,1]
[9,7]]
'''
print(arr[::-2,::2,::-2])

In [ ]:
'''
[[26 24]
[6 4]]
'''
print(arr[::-2,1,::-2])

In [ ]:
arr=np.array([
    [
        [1,20,4],
        [1,12,3],
        [11,2,5],
    ],
    [
        [1,20,4],
        [1,12,3],
        [11,2,5],
    ]
])

print(arr)
print(arr.ndim)

In [ ]:
arr=np.array([1,2,3,4])
print(arr[3])
print(arr[::2])
print(arr[::-2])


In [ ]:
arr=np.array([[1,2,3],
             [4,5,6]
             ])
print(arr[0])
print(arr[1])
print(arr[0][1])
print(arr[1][2])

In [ ]:
print(arr[0][1:3])
print(arr[1][1:3])
print(arr[0][1:2])
print(arr[1][1:2])

print(arr[1][::2])
print(arr[:,2])

In [ ]:
arr=np.array([
                [1,2,3],
                [4,5,6],
                [11,20,23],
                [14,56,68]

])
print(arr[[0, 3], [2, 2]])
print(arr[::3,2])
print(arr[0:2,1:3])


In [ ]:
print(arr[2:4,::2])
print(arr[1::2,::2])
print(arr[::3,::-2])


In [ ]:
arr=np.array([
                [1,2,3],
                [4,5,6],
                [11,20,23],
                [14,56,68]

])


'''
[3 2 1]
[6 5 4]
[23 20 11]
[68 56 14]
'''
'''
[68 56 14]
[23 20 11]
[6 5 4]
[3 2 1]
'''

In [ ]:
#to get elements of multiple list or 1D arrays from a 2D array
# we have to use arr[y_start_index:y_end_index:y_step,x_start_index:x_end_index:x_step] E.g: [::2,::2]
# we can't use arr[y_start_index:y_end_index:y_step][x_start_index:x_end_index:x_step] E.g:[::2][::2]
print(arr[:,::-1])

In [ ]:
print(arr[::-1,::-1])

In [ ]:
arr=np.array([
            [
               [1,2,3],
               [4,5,6]
            ],
            [
                 [11,12,13],
                 [14,15,16]
            ],
            [
                 [21,22,23],
                 [24,25,26]
             ]
])


In [ ]:
print(arr[0])
print(arr[1])
print(arr[2])

In [ ]:
print(arr[0][1])
print(arr[1][1])
print(arr[2][1])

In [ ]:
print(arr[:,:,:1])

In [ ]:
print(arr[:,:,:1])

In [ ]:
'''
[26 25 24]
[23 22 21]
[16 15 14]
[13 12 11]
[6 5 4]
[3 2 1]
'''


print(arr[::-1, ::-1, ::-1])

In [ ]:
arr=np.array([
            [
               [1,2,3],
               [4,5,6],
               [7,8,9]
            ],
            [
                 [11,12,13],
                 [14,15,16],
                 [17,18,19]
            ],
            [
                 [21,22,23],
                 [24,25,26],
                 [27,28,29]
             ]
])
'''
[[[ 9  7]
  [ 3  1]]

 [[29 27]
  [23 21]]]
'''

print(arr[::2,::-2,::-2])

print(arr[[1,2],[0,1],[0,2]])

12 feb

In [ ]:
# Check the given no by user is Kieth no or not
# a natural number that appears in a sequence where each term is
#the sum of the previous terms
# 47  = 4 7 11 18 29 47  .....
# 197 = 1 9 7 17 33 57 107 197 ....

In [ ]:
n=int(input("Enter the no: "))
temp=n
count=0
sum=0
l=[]
while n!=0:
    rem=n%10
    count+=1        # count of digit
    n//=10
    l.append(rem)   # list of digit
l=l[::-1]           # reverse to get the digits in correct order
print(l)
print(count)

while True:
  l=l[-count:]      # last n element as the count of digits
  s=0
  for x in l:
    s+=x            # sum of last n elements
  if s>temp:
    break           # break if sum is grester than that no if its kieth last will be that no else
  l.append(s)

if l[-1]==temp:
  print(f"{temp} is kieth no.")
else:
  print(f"{temp} is not kieth no.")











Enter the no: 5674
[5, 6, 7, 4]
4
5674 is not kieth no.


LCM

In [ ]:
import numpy as np

n1=4
n2=6

x=np.lcm(n1,n2)
x

12

In [ ]:
arr=np.array([3,6,9])
x=np.lcm.reduce(arr)
x

18

In [ ]:
arr=np.arange(1,11)
x=np.lcm.reduce(arr)
x

2520

GCD

In [ ]:
n1=9 #1,3
n2=6 #1,2,3

x=np.gcd(n1,n2)
x

3

In [ ]:
arr=np.array([20,18,12])
x=np.gcd.reduce(arr)
x

2

In [ ]:
arr=np.arange(1,11)
x=np.gcd.reduce(arr)
x

1

**Trignometric Func**

In [ ]:
x=np.sin(np.pi/2)
x

1.0

In [ ]:
arr=np.array([np.pi,np.pi/2,(2*np.pi)])
x=np.sin(arr)
x

array([ 1.2246468e-16,  1.0000000e+00, -2.4492936e-16])

In [ ]:
arr=np.array([90,180,270,360])

x=np.deg2rad(arr)

x

array([1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [ ]:
arr=np.array([np.pi,np.pi/2,(2*np.pi)])

x=np.rad2deg(arr)

x

array([180.,  90., 360.])

In [ ]:
x=np.arcsin(1)

x=np.rad2deg(x)

x

90.0

Hypotenues

In [ ]:
b=3
p=4
x=np.hypot(b,p)
x

5.0

Own ufunc

In [ ]:
def myadd(x,y):
  return x+y
madd=np.frompyfunc(myadd,2,1)
print(madd([1,2,3,4],[5,6,7,8]))


[6 8 10 12]


In [ ]:
def mysub(x,y):
  return x-y
msub=np.frompyfunc(mysub,2,1)
print(msub([1,2,3,4],[5,6,7,8]))

[-4 -4 -4 -4]


Matrices in NumPy



 Definition  

A matrix is a two-dimensional array in NumPy,

represented as a collection of rows and columns.

It is used for various mathematical operations

like addition, subtraction, multiplication, and inversion.



 Creating Matrices  

import numpy as np  



arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  

print(arr)  



 Matrix Operations  



 Addition of Matrices  

A = np.array([[1, 2], [3, 4]])  

B = np.array([[5, 6], [7, 8]])  

C = A + B  

print(C)  



 Subtraction of Matrices  

A = np.array([[10, 20], [30, 40]])  

B = np.array([[1, 2], [3, 4]])  

C = A - B  

print(C)  



 Matrix Multiplication (Element-wise)  

A = np.array([[1, 2], [3, 4]])  

B = np.array([[2, 0], [1, 2]])  

C = A * B  

print(C)  



 Matrix Dot Product  

A = np.array([[1, 2], [3, 4]])  

B = np.array([[2, 0], [1, 2]])  

C = np.dot(A, B)  

print(C)  



 Matrix Transpose  

A = np.array([[1, 2, 3], [4, 5, 6]])  

B = A.T  

print(B)

Matrix Inversion  

A = np.array([[1, 2], [3, 4]])  

B = np.linalg.inv(A)  

print(B)  



 Matrix Determinant  

A = np.array([[2, 3], [1, 4]])  

det = np.linalg.det(A)  

print(det)  



 Eigenvalues and Eigenvectors  

A = np.array([[4, -2], [1, 1]])  

eigenvalues, eigenvectors = np.linalg.eig(A)  

print(eigenvalues)  

print(eigenvectors)  



 Applications of Matrices  

- Image processing  

- Data transformations  

- Solving systems of linear equations  

- Graph and network analysis

In [ ]:
import numpy as np

# Define a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Compute the transpose
transpose_matrix = matrix.T
print(transpose_matrix)

[[1 4]
 [2 5]
 [3 6]]


17 feb


In [ ]:
import numpy as np

x=np.matrix([[1,2],[3,4]])
y=np.matrix([[4,5],[6,7]])
print(x)
print()
print(y)
print(type(y))

print("Addition")
print(x+y)

print("Subtraction")
print(x+y)

print("Multiplication")
print(x.dot(y)) # this is used for the matrix multiplication

print("Division")
print(x/y)


[[1 2]
 [3 4]]

[[4 5]
 [6 7]]
<class 'numpy.matrix'>
Addition
[[ 5  7]
 [ 9 11]]
Subtraction
[[ 5  7]
 [ 9 11]]
Multiplication
[[16 19]
 [36 43]]
Division
[[0.25       0.4       ]
 [0.5        0.57142857]]


In [ ]:
# transpose of matrix
x=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print("Original Matrix")
print(x)
print("Transpose Matrix")
print(np.transpose(x))

Original Matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose Matrix
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
# create 8x8 matrix and print the center of that matrix of size 4x4

x=np.ones((8,8),dtype=int)
print(x)
print(x[2:6,2:6])

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# create 8x8 matrix and print the center of that matrix of size 4x4
x=np.matrix(np.arange(1,65).reshape(8,8))
print(x)
print(x[2:6,2:6])

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
[[19 20 21 22]
 [27 28 29 30]
 [35 36 37 38]
 [43 44 45 46]]


18 feb


In [ ]:
# 1. Use np.zeros to create a 3x4 matrix of zeros and then replace the elements of the second row with ones. Print the updated matrix.

# 2. Create a 3D array of shape (2, 3, 4) filled with ones using np.ones. Then change the last column of each 2D sub-array to zeros and print the result.

# 3. Create a 5x5 identity matrix using np.eye. Multiply the elements in the diagonal by 3 and print the final matrix.

# 4. Using np.random.random, generate a 4x4 array of random float numbers between 0 and 1. Then replace all values greater than 0.5 with 1, and values less than or equal to 0.5 with 0. Print the modified array.

# 5. Generate 20 evenly spaced numbers between 0 and 100 using np.linspace. Then reshape the resulting array into a 4x5 matrix and print both the original and reshaped arrays.

# 6. Create a 3x3 array of random integers between 1 and 50 using np.random.randint. Use np.nditer to iterate over the array and print only the odd numbers.

# 7. Using np.ndenumerate, create a 4x3 array of random integers and print each element along with its index in the format index: element.

# 8. Generate a 1D array of 50 evenly spaced values between -10 and 10 using np.linspace. Reshape the array into a 5x10 matrix and use np.nditer to iterate over it. Print only the elements whose absolute value is greater than 5.

# 9. Using np.eye, create a 6x6 identity matrix. Then, with the help of np.ndenumerate, modify every even-indexed diagonal element by multiplying it by 2 and print the final matrix.

# 10. Create two random 3x3 matrices using np.random.random. Use np.nditer to iterate over both arrays simultaneously, print the corresponding elements from both matrices where the first matrix element is larger than the second matrix element.

In [ ]:
# 1. Use np.zeros to create a 3x4 matrix of zeros and then replace the elements of the second row with ones. Print the updated matrix.

import numpy as np

x=np.zeros((3,4))
print(x)
x[1]=1
print("After change")
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
After change
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]


In [ ]:
# 2. Create a 3D array of shape (2, 3, 4) filled with ones using np.ones. Then change the last column
# of each 2D sub-array to zeros and print the result.

In [ ]:
arr=np.ones((2,3,4))
print(arr)
print("After change")
arr[:,:,-1]=0
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
After change
[[[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]

 [[1. 1. 1. 0.]
  [1. 1. 1. 0.]
  [1. 1. 1. 0.]]]


In [ ]:
# 3. Create a 5x5 identity matrix using np.eye. Multiply the elements in the diagonal
# by 3 and print the final matrix.

x=np.eye(5)
print(x)
print("After change")
x=x*3
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
After change
[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]]


In [ ]:
 #4. Using np.random.random, generate a 4x4 array of random float numbers between 0 and 1.
 # Then replace all values greater than 0.5 with 1, and values less than or equal to 0.5 with 0. Print the modified array.

 arr=np.random.random((4,4))
 print(arr)
 print("After Change")
 arr[arr>0.5]=1
 arr[arr<=0.5]=0
 print(arr)

[[0.71358353 0.19455467 0.05231743 0.83974397]
 [0.80075933 0.22215938 0.93683796 0.74743125]
 [0.01525812 0.14177829 0.61792784 0.42079424]
 [0.99257134 0.88500412 0.99436637 0.65618144]]
After Change
[[1. 0. 0. 1.]
 [1. 0. 1. 1.]
 [0. 0. 1. 0.]
 [1. 1. 1. 1.]]


In [ ]:
# 5. Generate 20 evenly spaced numbers between 0 and 100 using np.linspace. Then reshape the resulting array into a 4x5 matrix and
#print both the original and reshaped arrays.
# arr=np.linspace(0,100,20)
# print(arr)
# x=arr.reshape(4,5)
# print("after change\n",x)


# Generate 20 evenly spaced numbers between 0 and 100
arr = np.linspace(0, 100, 20)
print("Original array:\n", arr)

# Reshape the array into a 4x5 matrix
reshaped_arr = arr.reshape(4, 5)
print("Reshaped array:\n", reshaped_arr)



Original array:
 [  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
Reshaped array:
 [[  0.           5.26315789  10.52631579  15.78947368  21.05263158]
 [ 26.31578947  31.57894737  36.84210526  42.10526316  47.36842105]
 [ 52.63157895  57.89473684  63.15789474  68.42105263  73.68421053]
 [ 78.94736842  84.21052632  89.47368421  94.73684211 100.        ]]


In [ ]:
# 6. Create a 3x3 array of random integers between 1 and 50 using np.random.randint. Use np.nditer
# to iterate over the array and print only the odd numbers.
arr=np.random.randint(1,50,(3,3))
print(arr)
print("After change")
for x in np.nditer(arr):
  if x%2!=0:
    print(x)

[[28 44 24]
 [33  7 43]
 [11 35 35]]
After change
33
7
43
11
35
35


In [ ]:
# 7. Using np.ndenumerate, create a 4x3 array of random integers and print each element along with
#its index in the format index: element.
arr=np.random.randint(1,50,(4,3))
print(arr)
print("After change")
for x in np.ndenumerate(arr):
  print(x)


[[18  7 36]
 [35  4 45]
 [49  1 19]
 [26 20 38]]
After change
((0, 0), 18)
((0, 1), 7)
((0, 2), 36)
((1, 0), 35)
((1, 1), 4)
((1, 2), 45)
((2, 0), 49)
((2, 1), 1)
((2, 2), 19)
((3, 0), 26)
((3, 1), 20)
((3, 2), 38)


In [ ]:

# 8. Generate a 1D array of 50 evenly spaced values between -10 and 10 using np.linspace. Reshape the array into a
# 5x10 matrix and use np.nditer to iterate over it.
#Print only the elements whose absolute value is greater than 5.
arr=np.linspace(-10,10,50).reshape(5,10)
print(arr)
for i in np.nditer(arr):
  if abs(i)>5:
    print(i)


[[-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
   -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061]
 [ -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
   -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796]
 [ -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
    0.20408163   0.6122449    1.02040816   1.42857143   1.83673469]
 [  2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
    4.28571429   4.69387755   5.10204082   5.51020408   5.91836735]
 [  6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
    8.36734694   8.7755102    9.18367347   9.59183673  10.        ]]
-10.0
-9.591836734693878
-9.183673469387756
-8.775510204081632
-8.36734693877551
-7.959183673469388
-7.551020408163265
-7.142857142857142
-6.73469387755102
-6.326530612244898
-5.918367346938775
-5.5102040816326525
-5.1020408163265305
5.1020408163265305
5.510204081632654
5.918367346938776
6.326530612244898
6.73469387755102


In [ ]:
# 9. Using np.eye, create a 6x6 identity matrix. Then, with the help of np.ndenumerate,
#modify every even-indexed diagonal element by multiplying it by 2 and print the final matrix.

arr=np.eye(6,6)
print(arr)

for index,elements in np.ndenumerate(arr):
  if index[0]%2==0 and index[1]%2==0:
    arr[index]=elements*2
print("After change")
print(arr)



[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
After change
[[2. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:

# 10. Create two random 3x3 matrices using np.random.random. Use np.nditer to iterate over both arrays simultaneously,
#print the corresponding elements from both matrices where the first matrix element is larger than the second matrix element.
x=np.random.random((3,3))
y=np.random.random((3,3))
print(x)
print(y)
for i,j in np.nditer([x,y]):
  if i>j:
    print(i,j)

[[0.12645118 0.46277895 0.11764529]
 [0.04874264 0.45368124 0.15129367]
 [0.12562822 0.86418857 0.99138486]]
[[0.6549619  0.01803179 0.0972021 ]
 [0.04369392 0.83229299 0.66828259]
 [0.59182954 0.71284526 0.33783011]]
0.46277894913243567 0.018031785096154218
0.11764528673287722 0.09720209610760744
0.04874263810625634 0.04369391909869513
0.8641885656871036 0.7128452560024242
0.9913848566335186 0.3378301091394096


In [ ]:
# 1. Use np.zeros to create a 3x3 matrix of zeros. Then replace the diagonal elements with the values [1, 2, 3] and print the final matrix.

# 2. Create a 4x4 array filled with ones using np.ones. Multiply every element in the array by 5 and print the updated array.

# 3. Create a 5x5 identity matrix using np.eye. Then, add 2 to all the elements of the matrix and print the final result.

# 4. Generate a 3x3 array of random float numbers between 0 and 1 using np.random.random. Replace all values greater than 0.7 with 0.7 and print both the original and modified arrays.

# 5. Use np.linspace to generate 15 evenly spaced numbers between 0 and 50. Reshape the array into a 3x5 matrix, and print both the original 1D array and the reshaped 2D matrix.

# 6. Create a 3x3 array of random integers between 1 and 20 using np.random.randint. Iterate over the array using np.nditer and print only the even numbers.

# 7. Using np.ndenumerate, create a 4x4 matrix of random integers between 10 and 50, and for each element, print the index and value if the value is divisible by 5.

# 8. Generate a 1D array of 20 evenly spaced values between -5 and 5 using np.linspace. Reshape the array into a 4x5 matrix and use np.nditer to print each element that is negative.

# 9. Create a 3x3 identity matrix using np.eye, and then with the help of np.ndenumerate, print the index and value of each diagonal element.

# 10. Create two 2x2 arrays of random integers between 1 and 10 using np.random.randint. Use np.nditer to iterate over both arrays simultaneously and print the corresponding elements where the first array's element is greater than the second array's element.

In [ ]:
# 1. Use np.zeros to create a 3x3 matrix of zeros. Then replace the diagonal elements with the values [1, 2, 3] and print the final matrix.
x=np.zeros((3,3))
print(x)
x[0,0]=1
x[1,1]=2
x[2,2]=3
print("After change \n",x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
After change 
 [[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [ ]:
# 2. Create a 4x4 array filled with ones using np.ones. Multiply every element in the array by 5 and print the updated array.

x=np.ones((4,4))
print(x)
print("Ater change")
print(x.dot(5))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [ ]:
# 3. Create a 5x5 identity matrix using np.eye. Then, add 2 to all the elements of the matrix and print the final result.
x=np.eye(5)
print(x)
print("After change")
print(x+2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
After change
[[3. 2. 2. 2. 2.]
 [2. 3. 2. 2. 2.]
 [2. 2. 3. 2. 2.]
 [2. 2. 2. 3. 2.]
 [2. 2. 2. 2. 3.]]


In [ ]:
# 4. Generate a 3x3 array of random float numbers between 0 and 1 using np.random.random. Replace all values greater than 0.7 with 0.7 and print both the original and modified arrays.
arr=np.random.random((3,3))
print(arr)
print("After change")
arr[arr>0.7]=0.7
print(arr)

[[0.15077942 0.2850571  0.03606263]
 [0.08378062 0.83890924 0.98285397]
 [0.92512626 0.01793926 0.82878921]]
After change
[[0.15077942 0.2850571  0.03606263]
 [0.08378062 0.7        0.7       ]
 [0.7        0.01793926 0.7       ]]


In [ ]:
# 5. Use np.linspace to generate 15 evenly spaced numbers between 0 and 50. Reshape the array into a 3x5 matrix,
# and print both the original 1D array and the reshaped 2D matrix.
arr=np.linspace(0,15,15)
print(arr)
arr.reshape(3,5)
print("After change")
print(arr)


[ 0.          1.07142857  2.14285714  3.21428571  4.28571429  5.35714286
  6.42857143  7.5         8.57142857  9.64285714 10.71428571 11.78571429
 12.85714286 13.92857143 15.        ]
After change
[ 0.          1.07142857  2.14285714  3.21428571  4.28571429  5.35714286
  6.42857143  7.5         8.57142857  9.64285714 10.71428571 11.78571429
 12.85714286 13.92857143 15.        ]


In [ ]:
# 6. Create a 3x3 array of random integers between 1 and 20 using np.random.randint. Iterate over the array using np.nditer and print only the even numbers.

x=np.random.randint(1,20,(3,3))
print(x)
print("After change")
for i in np.nditer(x):
  if i%2==0:
    print(i)


[[16 13 17]
 [ 3  3 15]
 [ 6  6 15]]
After change
16
6
6


In [ ]:

# 7. Using np.ndenumerate, create a 4x4 matrix of random integers between 10 and 50, and for each element, print the index and value if the value is divisible by 5.

x=np.random.randint(10,50,(4,4))
print(x)
print("After change")

for index,value in np.ndenumerate(x):
  if value%5==0:
    print(index,value)

[[19 26 46 23]
 [12 34 32 20]
 [45 28 20 14]
 [45 36 12 43]]
After change
(1, 3) 20
(2, 0) 45
(2, 2) 20
(3, 0) 45


In [ ]:
# 8. Generate a 1D array of 20 evenly spaced values between -5 and 5 using np.linspace. Reshape the array into a 4x5 matrix and
# use np.nditer to print each element that is negative.
arr=np.linspace(-5,5,20,(4,5))
print(arr)
for i in np.nditer(arr):
  if i<0:
    print(i)



[-5.         -4.47368421 -3.94736842 -3.42105263 -2.89473684 -2.36842105
 -1.84210526 -1.31578947 -0.78947368 -0.26315789  0.26315789  0.78947368
  1.31578947  1.84210526  2.36842105  2.89473684  3.42105263  3.94736842
  4.47368421  5.        ]
-5.0
-4.473684210526316
-3.947368421052632
-3.4210526315789473
-2.8947368421052633
-2.368421052631579
-1.8421052631578947
-1.3157894736842106
-0.7894736842105265
-0.2631578947368425


In [ ]:
# 9. Create a 3x3 identity matrix using np.eye, and then with the help of np.ndenumerate,
# print the index and value of each diagonal element.
x=np.eye(3)
print(x)

for index,value in np.ndenumerate(x):
  if index[0]==index[1]:
    print(index,value)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(0, 0) 1.0
(1, 1) 1.0
(2, 2) 1.0


In [ ]:

# 10. Create two 2x2 arrays of random integers between 1 and 10 using np.random.randint. Use np.nditer to iterate over
#both arrays simultaneously and print the corresponding elements where the first.

arr1=np.random.randint(1,10,(2,2))
arr2=np.random.randint(1,10,(2,2))
print(arr1)
print(arr2)
print("After change")
for i,j in np.nditer([arr1,arr2]):
  if i>j:
    print(i,j)

[[4 3]
 [7 5]]
[[5 2]
 [3 2]]
After change
3 2
7 3
5 2


In [ ]:
# !git config --global user.email "rishabhsrivastava606@gmail.com"
# !git config --global user.name "Rishabh"
!git config --list
# # To initialize git repo
# !git init

filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
user.email=rishabhsrivastava606@gmail.com
user.name=Rishabh
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/Rishabh6066/numpy_initial.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*


In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [ ]:
# !git add .
!git commit -m "numpy abhi tk ka progress"

[master (root-commit) 27ff88b] numpy abhi tk ka progress
 21 files changed, 51025 insertions(+)
 create mode 100644 .config/.last_opt_in_prompt.yaml
 create mode 100644 .config/.last_survey_prompt.yaml
 create mode 100644 .config/.last_update_check.json
 create mode 100644 .config/active_config
 create mode 100644 .config/config_sentinel
 create mode 100644 .config/configurations/config_default
 create mode 100644 .config/default_configs.db
 create mode 100644 .config/gce
 create mode 100644 .config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
 create mode 100644 .config/logs/2025.03.04/14.25.29.484800.log
 create mode 100644 .config/logs/2025.03.04/14.25.56.762625.log
 create mode 100644 .config/logs/2025.03.04/14.26.05.979204.log
 create mode 100644 .config/logs/2025.03.04/14.26.10.758958.log
 create mode 100644 .config/logs/2025.03.04/14.26.19.384068.log
 create mode 100644 .config/logs/2025.03.04/14.26.20.076126.log
 create mode 100755 sample_data/README.md
 creat

In [ ]:
# !git push

fatal: No configured push destination.
Either specify the URL from the command-line or configure a remote repository using

    git remote add <name> <url>

and then push using the remote name

    git push <name>



In [ ]:
# !git branch -M main
# !git remote set-url origin git@github.com:Rishabh6066/numpy_initial.git

In [ ]:
# # To generate rsa key

# !ssh-keygen -t rsa -b 4096 -C "rishabhsrivastava606@gmail.com"

In [ ]:
# To view teh rsa key

# !cat ~/.ssh/id_rsa.pub

In [ ]:
# # to connect to github

# !ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

# github.com:22 SSH-2.0-72017104c


In [ ]:
# # For pushing first time any repo to main

# !git push -u origin main

Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


In [ ]:
# !git remote add origin git@github.com:Rishabh6066/numpy_initial.git

error: remote origin already exists.


In [ ]:
# !git branch -M main

In [ ]:
# !git push -u origin main

Enumerating objects: 28, done.
Counting objects: 100% (28/28), done.
Delta compression using up to 2 threads
Compressing objects: 100% (21/21), done.
Writing objects: 100% (28/28), 8.42 MiB | 1.80 MiB/s, done.
Total 28 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), done.
To github.com:Rishabh6066/numpy_initial.git
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.


In [ ]:
# !git log

commit 27ff88be250ab4d317200193df7c15e706ea0108 (HEAD -> main, origin/main)
Author: Rishabh <rishabhsrivastava606@gmail.com>
Date:   Thu Mar 6 17:21:15 2025 +0000

    numpy abhi tk ka progress


In [ ]:
!git branch

* main


Switched to a new branch 'b-01'


commit 27ff88be250ab4d317200193df7c15e706ea0108 (HEAD -> main, origin/main, origin/HEAD)
Author: Rishabh <rishabhsrivastava606@gmail.com>
Date:   Thu Mar 6 17:21:15 2025 +0000

    numpy abhi tk ka progress
